/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Traccar) {
      root.Traccar = {};
    }
    root.Traccar.DeviceTotalDistance = factory(root.Traccar.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceTotalDistance model module.
   * @module model/DeviceTotalDistance
   * @version 4.0
   */

  /**
   * Constructs a new <code>DeviceTotalDistance</code>.
   * @alias module:model/DeviceTotalDistance
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>DeviceTotalDistance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceTotalDistance} obj Optional instance to populate.
   * @return {module:model/DeviceTotalDistance} The populated <code>DeviceTotalDistance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceId')) {
        obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'Number');
      }
      if (data.hasOwnProperty('totalDistance')) {
        obj['totalDistance'] = ApiClient.convertToType(data['totalDistance'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} deviceId
   */
  exports.prototype['deviceId'] = undefined;
  /**
   * in meters
   * @member {Number} totalDistance
   */
  exports.prototype['totalDistance'] = undefined;



  return exports;
}));


