/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ERRORUNKNOWN'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ERRORUNKNOWN'));
  } else {
    // Browser globals (root is window)
    if (!root.Traccar) {
      root.Traccar = {};
    }
    root.Traccar.Notification = factory(root.Traccar.ApiClient, root.Traccar.ERRORUNKNOWN);
  }
}(this, function(ApiClient, ERRORUNKNOWN) {
  'use strict';




  /**
   * The Notification model module.
   * @module model/Notification
   * @version 4.0
   */

  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notification} obj Optional instance to populate.
   * @return {module:model/Notification} The populated <code>Notification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('always')) {
        obj['always'] = ApiClient.convertToType(data['always'], 'Boolean');
      }
      if (data.hasOwnProperty('web')) {
        obj['web'] = ApiClient.convertToType(data['web'], 'Boolean');
      }
      if (data.hasOwnProperty('mail')) {
        obj['mail'] = ApiClient.convertToType(data['mail'], 'Boolean');
      }
      if (data.hasOwnProperty('sms')) {
        obj['sms'] = ApiClient.convertToType(data['sms'], 'Boolean');
      }
      if (data.hasOwnProperty('calendarId')) {
        obj['calendarId'] = ApiClient.convertToType(data['calendarId'], 'Number');
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], ERRORUNKNOWN);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Boolean} always
   */
  exports.prototype['always'] = undefined;
  /**
   * @member {Boolean} web
   */
  exports.prototype['web'] = undefined;
  /**
   * @member {Boolean} mail
   */
  exports.prototype['mail'] = undefined;
  /**
   * @member {Boolean} sms
   */
  exports.prototype['sms'] = undefined;
  /**
   * @member {Number} calendarId
   */
  exports.prototype['calendarId'] = undefined;
  /**
   * @member {module:model/ERRORUNKNOWN} attributes
   */
  exports.prototype['attributes'] = undefined;



  return exports;
}));


