/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Traccar) {
      root.Traccar = {};
    }
    root.Traccar.ReportStops = factory(root.Traccar.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReportStops model module.
   * @module model/ReportStops
   * @version 4.0
   */

  /**
   * Constructs a new <code>ReportStops</code>.
   * @alias module:model/ReportStops
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>ReportStops</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportStops} obj Optional instance to populate.
   * @return {module:model/ReportStops} The populated <code>ReportStops</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceId')) {
        obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'Number');
      }
      if (data.hasOwnProperty('deviceName')) {
        obj['deviceName'] = ApiClient.convertToType(data['deviceName'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('lat')) {
        obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
      }
      if (data.hasOwnProperty('lon')) {
        obj['lon'] = ApiClient.convertToType(data['lon'], 'Number');
      }
      if (data.hasOwnProperty('endTime')) {
        obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
      }
      if (data.hasOwnProperty('spentFuel')) {
        obj['spentFuel'] = ApiClient.convertToType(data['spentFuel'], 'Number');
      }
      if (data.hasOwnProperty('engineHours')) {
        obj['engineHours'] = ApiClient.convertToType(data['engineHours'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} deviceId
   */
  exports.prototype['deviceId'] = undefined;
  /**
   * @member {String} deviceName
   */
  exports.prototype['deviceName'] = undefined;
  /**
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
   * @member {Date} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {Number} lat
   */
  exports.prototype['lat'] = undefined;
  /**
   * @member {Number} lon
   */
  exports.prototype['lon'] = undefined;
  /**
   * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
   * @member {Date} endTime
   */
  exports.prototype['endTime'] = undefined;
  /**
   * in liters
   * @member {Number} spentFuel
   */
  exports.prototype['spentFuel'] = undefined;
  /**
   * @member {Number} engineHours
   */
  exports.prototype['engineHours'] = undefined;



  return exports;
}));


