/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ERRORUNKNOWN'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ERRORUNKNOWN'));
  } else {
    // Browser globals (root is window)
    if (!root.Traccar) {
      root.Traccar = {};
    }
    root.Traccar.Server = factory(root.Traccar.ApiClient, root.Traccar.ERRORUNKNOWN);
  }
}(this, function(ApiClient, ERRORUNKNOWN) {
  'use strict';




  /**
   * The Server model module.
   * @module model/Server
   * @version 4.0
   */

  /**
   * Constructs a new <code>Server</code>.
   * @alias module:model/Server
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>Server</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Server} obj Optional instance to populate.
   * @return {module:model/Server} The populated <code>Server</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('registration')) {
        obj['registration'] = ApiClient.convertToType(data['registration'], 'Boolean');
      }
      if (data.hasOwnProperty('readonly')) {
        obj['readonly'] = ApiClient.convertToType(data['readonly'], 'Boolean');
      }
      if (data.hasOwnProperty('deviceReadonly')) {
        obj['deviceReadonly'] = ApiClient.convertToType(data['deviceReadonly'], 'Boolean');
      }
      if (data.hasOwnProperty('limitCommands')) {
        obj['limitCommands'] = ApiClient.convertToType(data['limitCommands'], 'Boolean');
      }
      if (data.hasOwnProperty('map')) {
        obj['map'] = ApiClient.convertToType(data['map'], 'String');
      }
      if (data.hasOwnProperty('bingKey')) {
        obj['bingKey'] = ApiClient.convertToType(data['bingKey'], 'String');
      }
      if (data.hasOwnProperty('mapUrl')) {
        obj['mapUrl'] = ApiClient.convertToType(data['mapUrl'], 'String');
      }
      if (data.hasOwnProperty('poiLayer')) {
        obj['poiLayer'] = ApiClient.convertToType(data['poiLayer'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('zoom')) {
        obj['zoom'] = ApiClient.convertToType(data['zoom'], 'Number');
      }
      if (data.hasOwnProperty('twelveHourFormat')) {
        obj['twelveHourFormat'] = ApiClient.convertToType(data['twelveHourFormat'], 'Boolean');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('forceSettings')) {
        obj['forceSettings'] = ApiClient.convertToType(data['forceSettings'], 'Boolean');
      }
      if (data.hasOwnProperty('coordinateFormat')) {
        obj['coordinateFormat'] = ApiClient.convertToType(data['coordinateFormat'], 'String');
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], ERRORUNKNOWN);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} registration
   */
  exports.prototype['registration'] = undefined;
  /**
   * @member {Boolean} readonly
   */
  exports.prototype['readonly'] = undefined;
  /**
   * @member {Boolean} deviceReadonly
   */
  exports.prototype['deviceReadonly'] = undefined;
  /**
   * @member {Boolean} limitCommands
   */
  exports.prototype['limitCommands'] = undefined;
  /**
   * @member {String} map
   */
  exports.prototype['map'] = undefined;
  /**
   * @member {String} bingKey
   */
  exports.prototype['bingKey'] = undefined;
  /**
   * @member {String} mapUrl
   */
  exports.prototype['mapUrl'] = undefined;
  /**
   * @member {String} poiLayer
   */
  exports.prototype['poiLayer'] = undefined;
  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {Number} zoom
   */
  exports.prototype['zoom'] = undefined;
  /**
   * @member {Boolean} twelveHourFormat
   */
  exports.prototype['twelveHourFormat'] = undefined;
  /**
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * @member {Boolean} forceSettings
   */
  exports.prototype['forceSettings'] = undefined;
  /**
   * @member {String} coordinateFormat
   */
  exports.prototype['coordinateFormat'] = undefined;
  /**
   * @member {module:model/ERRORUNKNOWN} attributes
   */
  exports.prototype['attributes'] = undefined;



  return exports;
}));


