/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Traccar) {
      root.Traccar = {};
    }
    root.Traccar.Statistics = factory(root.Traccar.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Statistics model module.
   * @module model/Statistics
   * @version 4.0
   */

  /**
   * Constructs a new <code>Statistics</code>.
   * @alias module:model/Statistics
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Statistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Statistics} obj Optional instance to populate.
   * @return {module:model/Statistics} The populated <code>Statistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('captureTime')) {
        obj['captureTime'] = ApiClient.convertToType(data['captureTime'], 'Date');
      }
      if (data.hasOwnProperty('activeUsers')) {
        obj['activeUsers'] = ApiClient.convertToType(data['activeUsers'], 'Number');
      }
      if (data.hasOwnProperty('activeDevices')) {
        obj['activeDevices'] = ApiClient.convertToType(data['activeDevices'], 'Number');
      }
      if (data.hasOwnProperty('requests')) {
        obj['requests'] = ApiClient.convertToType(data['requests'], 'Number');
      }
      if (data.hasOwnProperty('messagesReceived')) {
        obj['messagesReceived'] = ApiClient.convertToType(data['messagesReceived'], 'Number');
      }
      if (data.hasOwnProperty('messagesStored')) {
        obj['messagesStored'] = ApiClient.convertToType(data['messagesStored'], 'Number');
      }
    }
    return obj;
  }

  /**
   * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
   * @member {Date} captureTime
   */
  exports.prototype['captureTime'] = undefined;
  /**
   * @member {Number} activeUsers
   */
  exports.prototype['activeUsers'] = undefined;
  /**
   * @member {Number} activeDevices
   */
  exports.prototype['activeDevices'] = undefined;
  /**
   * @member {Number} requests
   */
  exports.prototype['requests'] = undefined;
  /**
   * @member {Number} messagesReceived
   */
  exports.prototype['messagesReceived'] = undefined;
  /**
   * @member {Number} messagesStored
   */
  exports.prototype['messagesStored'] = undefined;



  return exports;
}));


