/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Traccar);
  }
}(this, function(expect, Traccar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Traccar.Permission();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Permission', function() {
    it('should create an instance of Permission', function() {
      // uncomment below and update the code to test Permission
      //var instane = new Traccar.Permission();
      //expect(instance).to.be.a(Traccar.Permission);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property geofenceId (base name: "geofenceId")', function() {
      // uncomment below and update the code to test the property geofenceId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property calendarId (base name: "calendarId")', function() {
      // uncomment below and update the code to test the property calendarId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property attributeId (base name: "attributeId")', function() {
      // uncomment below and update the code to test the property attributeId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property driverId (base name: "driverId")', function() {
      // uncomment below and update the code to test the property driverId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

    it('should have the property managedUserId (base name: "managedUserId")', function() {
      // uncomment below and update the code to test the property managedUserId
      //var instane = new Traccar.Permission();
      //expect(instance).to.be();
    });

  });

}));
