/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Traccar);
  }
}(this, function(expect, Traccar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Traccar.ReportSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportSummary', function() {
    it('should create an instance of ReportSummary', function() {
      // uncomment below and update the code to test ReportSummary
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be.a(Traccar.ReportSummary);
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property deviceName (base name: "deviceName")', function() {
      // uncomment below and update the code to test the property deviceName
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property maxSpeed (base name: "maxSpeed")', function() {
      // uncomment below and update the code to test the property maxSpeed
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property averageSpeed (base name: "averageSpeed")', function() {
      // uncomment below and update the code to test the property averageSpeed
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property spentFuel (base name: "spentFuel")', function() {
      // uncomment below and update the code to test the property spentFuel
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

    it('should have the property engineHours (base name: "engineHours")', function() {
      // uncomment below and update the code to test the property engineHours
      //var instane = new Traccar.ReportSummary();
      //expect(instance).to.be();
    });

  });

}));
