/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Traccar);
  }
}(this, function(expect, Traccar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Traccar.ReportTrips();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportTrips', function() {
    it('should create an instance of ReportTrips', function() {
      // uncomment below and update the code to test ReportTrips
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be.a(Traccar.ReportTrips);
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property deviceName (base name: "deviceName")', function() {
      // uncomment below and update the code to test the property deviceName
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property maxSpeed (base name: "maxSpeed")', function() {
      // uncomment below and update the code to test the property maxSpeed
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property averageSpeed (base name: "averageSpeed")', function() {
      // uncomment below and update the code to test the property averageSpeed
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property spentFuel (base name: "spentFuel")', function() {
      // uncomment below and update the code to test the property spentFuel
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property startAddress (base name: "startAddress")', function() {
      // uncomment below and update the code to test the property startAddress
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property startLat (base name: "startLat")', function() {
      // uncomment below and update the code to test the property startLat
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property startLon (base name: "startLon")', function() {
      // uncomment below and update the code to test the property startLon
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "endTime")', function() {
      // uncomment below and update the code to test the property endTime
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property endAddress (base name: "endAddress")', function() {
      // uncomment below and update the code to test the property endAddress
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property endLat (base name: "endLat")', function() {
      // uncomment below and update the code to test the property endLat
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property endLon (base name: "endLon")', function() {
      // uncomment below and update the code to test the property endLon
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property driverUniqueId (base name: "driverUniqueId")', function() {
      // uncomment below and update the code to test the property driverUniqueId
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

    it('should have the property driverName (base name: "driverName")', function() {
      // uncomment below and update the code to test the property driverName
      //var instane = new Traccar.ReportTrips();
      //expect(instance).to.be();
    });

  });

}));
