/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Traccar);
  }
}(this, function(expect, Traccar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Traccar.Server();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Server', function() {
    it('should create an instance of Server', function() {
      // uncomment below and update the code to test Server
      //var instane = new Traccar.Server();
      //expect(instance).to.be.a(Traccar.Server);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property registration (base name: "registration")', function() {
      // uncomment below and update the code to test the property registration
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property readonly (base name: "readonly")', function() {
      // uncomment below and update the code to test the property readonly
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property deviceReadonly (base name: "deviceReadonly")', function() {
      // uncomment below and update the code to test the property deviceReadonly
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property limitCommands (base name: "limitCommands")', function() {
      // uncomment below and update the code to test the property limitCommands
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property map (base name: "map")', function() {
      // uncomment below and update the code to test the property map
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property bingKey (base name: "bingKey")', function() {
      // uncomment below and update the code to test the property bingKey
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property mapUrl (base name: "mapUrl")', function() {
      // uncomment below and update the code to test the property mapUrl
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property poiLayer (base name: "poiLayer")', function() {
      // uncomment below and update the code to test the property poiLayer
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property zoom (base name: "zoom")', function() {
      // uncomment below and update the code to test the property zoom
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property twelveHourFormat (base name: "twelveHourFormat")', function() {
      // uncomment below and update the code to test the property twelveHourFormat
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property forceSettings (base name: "forceSettings")', function() {
      // uncomment below and update the code to test the property forceSettings
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property coordinateFormat (base name: "coordinateFormat")', function() {
      // uncomment below and update the code to test the property coordinateFormat
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instane = new Traccar.Server();
      //expect(instance).to.be();
    });

  });

}));
