/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Traccar);
  }
}(this, function(expect, Traccar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Traccar.Statistics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Statistics', function() {
    it('should create an instance of Statistics', function() {
      // uncomment below and update the code to test Statistics
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be.a(Traccar.Statistics);
    });

    it('should have the property captureTime (base name: "captureTime")', function() {
      // uncomment below and update the code to test the property captureTime
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property activeUsers (base name: "activeUsers")', function() {
      // uncomment below and update the code to test the property activeUsers
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property activeDevices (base name: "activeDevices")', function() {
      // uncomment below and update the code to test the property activeDevices
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property requests (base name: "requests")', function() {
      // uncomment below and update the code to test the property requests
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property messagesReceived (base name: "messagesReceived")', function() {
      // uncomment below and update the code to test the property messagesReceived
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

    it('should have the property messagesStored (base name: "messagesStored")', function() {
      // uncomment below and update the code to test the property messagesStored
      //var instane = new Traccar.Statistics();
      //expect(instance).to.be();
    });

  });

}));
